web:
   image: nginx:latest
   ports:
      - "8089:80"
   volumes:
      - .:/usr/src
      - .phpConf/site.conf:/etc/nginx/conf.d/default.conf
   links:
      - php
      - mysql

php:
   image: php-sql
   volumes:
      - .:/usr/src
   links:
     - mysql

mysql:
   image: mysql:5.7.27
   ports:
      - "33306:3306"
   environment:
      - MYSQL_DATABASES=sturesy
      - MYSQL_ROOT_PASSWORD=584n43jt8943bt3e4as
      - MYSQL_PORT=3306
      - MYSQL_HOST=localhost
